name: Simple Windows Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Setup vcpkg (classic mode)
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: "120deac3062162151622ca4860575a33844ba10b"
          runVcpkgInstall: false
      
      - name: Install opus only
        run: |
          C:\vcpkg\vcpkg install opus:x64-windows-static --recurse --classic
        shell: cmd
      
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.5'
          channel: stable
      
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: '1.75'
          targets: x86_64-pc-windows-msvc
      
      - name: Build
        run: python build.py --flutter --portable
        env:
          VCPKG_ROOT: C:\vcpkg
      
      - uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: ./flutter/build/windows/x64/runner/Release/
